version: '3.9'
services:

  app:
    build:
      context: ./../../
      dockerfile: ./docker/debug/Dockerfile
    container_name: app-debug
    image: app-debug
    #environment:
    ports:
      - 8080:8080
      - 4000:4000
    env_file: ./../.env
    depends_on:
      - postgres
#    volumes:
#      - ./logs/:/app/logs/

  postgres:
    container_name: postgres-debug
    image: postgres:14-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
      #- .//logs:/logs
    #command: postgres -c logging_collector=on -c log_rotation_age=1440  -c log_truncate_on_rotation=true -c log_file_mode=0777 -c log_destination=stderr -c log_directory=/logs -c client_min_messages=notice -c log_min_messages=warning -c log_min_duration_statement=-1 -c log_statement=all  -c log_connections=0
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    ports:
      - "${PG_PORT}:5432"

volumes:
  pg-data:
