version: '3.9'
services:

  app:
    build:
      context: ./../../
      dockerfile: ./docker/prod/Dockerfile
    container_name: app
    image: app
    ports:
      - 8080:8080
    env_file: ./../.env
    depends_on:
      - postgres
    volumes:
      - ./logs/:/logs/

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    ports:
      - "${PG_PORT}:5432"

volumes:
  pg-data:
