app:
  name: 'test-treasury'
  version: '1.0.0'

http:
  port: '8080'

# конфигурация сервиса логирования
log:
    path: "/app/logs/"
    error_file: "error.log"
    debug_file: "debug.log"

postgres:
  user: user
  password: pass
  host: postgres
  port: 5432
  db_name: postgres
  max_pool_size: 2
  conn_attempts: 10
